/**
 * PDF eyeball probe — generates a kitchen-sink document with the direct
 * PDF writer and emits the bytes as base64 in #lm-probe, so tooling can
 * save the file and a human (or agent) can open it. Not a pass/fail
 * gate; probe-editor.ts covers those.
 */
import { htmlToPdf } from '@lemonadejs/editor';

const run = async () => {
    const cv = document.createElement('canvas');
    cv.width = 240;
    cv.height = 80;
    const g = cv.getContext('2d')!;
    const grad = g.createLinearGradient(0, 0, 240, 0);
    grad.addColorStop(0, '#2563eb');
    grad.addColorStop(1, '#c62828');
    g.fillStyle = grad;
    g.fillRect(0, 0, 240, 80);
    g.fillStyle = '#fff';
    g.font = 'bold 20px Arial';
    g.fillText('canvas image', 60, 48);

    const html = [
        '<h1>The Editor block — direct PDF</h1>',
        '<p>Generated <b>locally</b> by the <i>zero-dependency</i> writer: ',
        '<u>underline</u>, <s>strike</s>, <sub>sub</sub>, <sup>sup</sup>, ',
        '<span style="color:#c62828">colored text</span>, ',
        '<span style="background-color:#fff59d">highlight</span> and a ',
        '<a href="https://lemonadejs.com">real link annotation</a>.</p>',
        '<h2>A table with structure</h2>',
        '<table><colgroup><col style="width:120px"><col style="width:220px"><col style="width:220px"></colgroup><tbody>',
        '<tr><th>Block</th><th>What it does</th><th>Notes</th></tr>',
        '<tr><td rowspan="2">Editor</td><td>tables, images, colors</td><td style="background-color:#e8f5e9">merged cell left</td></tr>',
        '<tr><td colspan="2" style="text-align:center">a colspan pair, centered</td></tr>',
        '</tbody></table>',
        '<h2>Lists and quotes</h2>',
        '<ul><li>bulleted item</li><li>second item</li></ul>',
        '<ol><li>numbered item</li><li>another</li></ol>',
        '<blockquote>Blockquotes carry the grey bar and muted ink.</blockquote>',
        '<pre>const pdf = await htmlToPdf(html);</pre>',
        '<p style="text-align:center"><img src="' + cv.toDataURL('image/png') + '"></p>',
        '<hr><p style="text-align:right">right-aligned closing line</p>',
    ].join('');

    const bytes = await htmlToPdf(html, { title: 'Editor direct PDF' });
    let b64 = '';
    for (let i = 0; i < bytes.length; i += 0x8000) {
        b64 += String.fromCharCode(...Array.from(bytes.slice(i, i + 0x8000)));
    }
    const pre = document.createElement('pre');
    pre.id = 'lm-probe';
    // open with #full to get the bytes (save + eyeball); the plain run
    // stays quiet so `npm run probe` output is readable
    const payload = location.hash === '#full' ? '\nPDFB64:' + btoa(b64) : '';
    pre.textContent = '\nLM-PROBE-BEGIN\nPASS pdf-generated bytes=' + bytes.length + payload + '\nLM-PROBE-END\n';
    document.body.appendChild(pre);
};

run().catch((e) => {
    const pre = document.createElement('pre');
    pre.id = 'lm-probe';
    pre.textContent = '\nLM-PROBE-BEGIN\nERROR ' + (e && (e as Error).message) + '\nLM-PROBE-END\n';
    document.body.appendChild(pre);
});
